name: build-and-push

on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '**.md'


jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set short_sha for Image tag
        id: short_sha
        run: echo "::set-output name=short_sha::$(echo $GITHUB_SHA | cut -c1-7)"

      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          repository: AppFlowy-IO/AppFlowy-Cloud

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push Appflowy
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ghcr.io/bym0/appflowy:${{ steps.short_sha.outputs.short_sha }}
          platforms: linux/amd64
          context: .

      - name: Build and push gotrue
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ghcr.io/bym0/appflowy-gotrue:${{ steps.short_sha.outputs.short_sha }}
          platforms: linux/amd64
          context: .
          file: docker/gotrue.Dockerfile
